# Generated by Django 5.0.1 on 2024-01-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_alter_customer_phone_alter_shippingaddress_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
